chore: add generated files for jwt role
topfreegames/crossplane-provider-vault pull request #1
Opened 2022-10-12 14:33 UTC by RonnanSouza

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2022-10-24 17:14 UTC, beuleal commented on internal/controller/jwt/jwt_test.go
> +				t.Errorf("\n%s\ne.Observe(...): -want error, +got error:\n%s\n", tc.reason, diff)
should it be Create instead Observe? The next line too

2022-10-24 17:15 UTC, beuleal commented on internal/controller/jwt/jwt_test.go
> +				t.Errorf("\n%s\ne.Observe(...): -want error, +got error:\n%s\n", tc.reason, diff)
Same typo issue s/Observe/Update

2022-10-24 17:15 UTC, beuleal commented on internal/controller/jwt/jwt_test.go
> +				t.Errorf("\n%s\ne.Observe(...): -want error, +got error:\n%s\n", tc.reason, diff)
s/Observe/Delete

2022-10-24 17:17 UTC, beuleal commented
Don't we need to validate fields between fields?

2022-10-24 18:11 UTC, RonnanSouza commented
> Don't we need to validate fields between fields?

Actually, I'm doing the validations in the CRD itself.

2022-10-25 14:04 UTC, beuleal requested changes

2022-10-25 14:04 UTC, beuleal commented on internal/controller/jwt/vault.go
> +	if role.RoleType == "jwt" && len(role.BoundAudiences) == 0 {
As the first part of each `if` statement are the same for all validations, we can refactor them, example:
```
if role.RoleType == "jwt" {
    if len(...) == 0 {
      return error
   }
   if...
   if...

}
```

2022-10-25 21:14 UTC, beuleal commented
LGTM! Great work buddy!

2022-10-25 21:15 UTC, beuleal approved these changes

2022-10-25 21:16 UTC, merged